include("./../../src/Lar.jl")

include("./randomarrangement2d.jl")
include("./randomshapes.jl")
include("./stresstest2d.jl")
include("./svg2lar.jl")

randomarrangement2d(100)
randomshapes(100)
stresstest2d()
#svgarrangement("./test/svg/new.svg")
#svgarrangement("./test/svg/curved.svg")
#svgarrangement("./test/svg/twopaths.svg")
#svgarrangement("./test/svg/paths.svg")
#svgarrangement("./test/svg/boundarytest2.svg")
#svgarrangement("./test/svg/tile.svg")
#svgarrangement("./test/svg/interior.svg")
svgarrangement("./test/svg/holes.svg")
#svgarrangement("./test/svg/LAR.svg")
